# Generated by Django 5.0.6 on 2024-07-31 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appescuela', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='comision',
            field=models.IntegerField(null=True),
        ),
    ]
